version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: testelocalize-api
    ports:
      - "5000:80"        
    env_file:
      - TesteLocalize.WebAPI/.env     
    depends_on:
      - db
  db:
    image: postgres:16
    container_name: testelocalize-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: TesteLocalizeDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  
  
